---

name: git actions

on:
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env :
      AWS_ACCESS_KEY_ID: ${{secrets.access_key}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.secret_key}}
      AWS_DEFAULT_REGION: "ap-southeast-2"
      PACKER_VERSION: "1.14.2"

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate
      

      - name: Apply only if changes detected
        if: ${{ steps.tfplan.outputs.plan_exitcode == '2' }}
        run: |
          echo "Changes detected by terraform plan — applying..."
          terraform -chdir=terraform apply -input=false -auto-approve tfplan

      - name: Skip apply if no changes
        if: ${{ steps.tfplan.outputs.plan_exitcode == '0' }}
        run: echo "No changes detected — skipping apply."

      - name: Fail if plan errored
        if: ${{ steps.tfplan.outputs.plan_exitcode == '1' }}
        run: |
          echo "Terraform plan failed (exit code 1). See plan.out above."
          exit 1
